package com.jrejaud.twiliolookup.Networking;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Created by jrejaud on 3/16/16.
 * Generated by "org.jsonschema2pojo"
 */
public class TwilioLookupResponse {

    @SerializedName("caller_name")
    @Expose
    private Object callerName;
    @SerializedName("country_code")
    @Expose
    private String countryCode;
    @SerializedName("phone_number")
    @Expose
    private String phoneNumber;
    @SerializedName("national_format")
    @Expose
    private String nationalFormat;
    @SerializedName("carrier")
    @Expose
    private TwilioLookupResponseCarrier carrier;
    @SerializedName("url")
    @Expose
    private String url;

    /**
     *
     * @return
     * The callerName
     */
    public Object getCallerName() {
        return callerName;
    }

    /**
     *
     * @param callerName
     * The caller_name
     */
    public void setCallerName(Object callerName) {
        this.callerName = callerName;
    }

    /**
     *
     * @return
     * The countryCode
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     *
     * @param countryCode
     * The country_code
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     *
     * @return
     * The phoneNumber
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     *
     * @param phoneNumber
     * The phone_number
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     *
     * @return
     * The nationalFormat
     */
    public String getNationalFormat() {
        return nationalFormat;
    }

    /**
     *
     * @param nationalFormat
     * The national_format
     */
    public void setNationalFormat(String nationalFormat) {
        this.nationalFormat = nationalFormat;
    }

    /**
     *
     * @return
     * The twilioLookupResponseCarrier
     */
    public TwilioLookupResponseCarrier getCarrier() {
        return carrier;
    }

    /**
     *
     * @param carrier
     * The twilioLookupResponseCarrier
     */
    public void setCarrier(TwilioLookupResponseCarrier carrier) {
        this.carrier = carrier;
    }

    /**
     *
     * @return
     * The url
     */
    public String getUrl() {
        return url;
    }

    /**
     *
     * @param url
     * The url
     */
    public void setUrl(String url) {
        this.url = url;
    }
}