package com.jrejaud.twiliolookup;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Created by jrejaud on 3/16/16.
 * Generated by "org.jsonschema2pojo"
 */
public class TwilioLookupResponseCarrier {

    @SerializedName("mobile_country_code")
    @Expose
    private String mobileCountryCode;
    @SerializedName("mobile_network_code")
    @Expose
    private String mobileNetworkCode;
    @SerializedName("name")
    @Expose
    private String name;
    @SerializedName("type")
    @Expose
    private String type;
    @SerializedName("error_code")
    @Expose
    private Object errorCode;

    /**
     * @return The mobileCountryCode
     */
    public String getMobileCountryCode() {
        return mobileCountryCode;
    }

    /**
     * @param mobileCountryCode The mobile_country_code
     */
    protected void setMobileCountryCode(String mobileCountryCode) {
        this.mobileCountryCode = mobileCountryCode;
    }

    /**
     * @return The mobileNetworkCode
     */
    public String getMobileNetworkCode() {
        return mobileNetworkCode;
    }

    /**
     * @param mobileNetworkCode The mobile_network_code
     */
    protected void setMobileNetworkCode(String mobileNetworkCode) {
        this.mobileNetworkCode = mobileNetworkCode;
    }

    /**
     * @return The name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name The name
     */
    protected void setName(String name) {
        this.name = name;
    }

    /**
     * @return The type
     */
    public String getType() {
        return type;
    }

    /**
     * @param type The type
     */
    protected void setType(String type) {
        this.type = type;
    }

    /**
     * @return The errorCode
     */
    public Object getErrorCode() {
        return errorCode;
    }

    /**
     * @param errorCode The error_code
     */
    protected void setErrorCode(Object errorCode) {
        this.errorCode = errorCode;
    }

}

