package com.jrejaud.twiliolookup;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Created by jrejaud on 3/16/16.
 * Generated by "org.jsonschema2pojo"
 */
public class TwilioLookupInvalidResponse {
    @SerializedName("status")
    @Expose
    private Integer status;
    @SerializedName("more_info")
    @Expose
    private String moreInfo;
    @SerializedName("code")
    @Expose
    private Integer code;
    @SerializedName("message")
    @Expose
    private String message;

    /**
     *
     * @return
     * The status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     *
     * @param status
     * The status
     */
    protected void setStatus(Integer status) {
        this.status = status;
    }

    /**
     *
     * @return
     * The moreInfo
     */
    public String getMoreInfo() {
        return moreInfo;
    }

    /**
     *
     * @param moreInfo
     * The more_info
     */
    protected void setMoreInfo(String moreInfo) {
        this.moreInfo = moreInfo;
    }

    /**
     *
     * @return
     * The code
     */
    public Integer getCode() {
        return code;
    }

    /**
     *
     * @param code
     * The code
     */
    protected void setCode(Integer code) {
        this.code = code;
    }

    /**
     *
     * @return
     * The message
     */
    public String getMessage() {
        return message;
    }

    /**
     *
     * @param message
     * The message
     */
    protected void setMessage(String message) {
        this.message = message;
    }
}
